# Generated by Django 5.2.8 on 2025-11-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prifile_img',
            new_name='profile_img',
        ),
    ]
