# Generated by Django 5.2.8 on 2025-12-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
